################################################################################
# OG1 VARIABLE AND SENSOR MAPPING CONFIGURATION
#
# Purpose: Converts local dataset variables and sensor names into the
# OceanGlider 1 (OG1) standard format.
#
# Logic:
# 1. Variables are renamed from raw internal names to OG1-compliant keys.
# 2. Sensors are mapped from global attributes to their official designations.
# 3. Detailed instrument metadata for these sensors is pulled from:
#    OG1_sensor_attrs.yaml (sourced from NERC L22/SeaVoX Catalogue).
################################################################################
#### VARIABLE RENAMING (Raw -> OG1 Standard) ####
latitude: LATITUDE
longitude: LONGITUDE
gps_lat: LATITUDE_GPS
gps_lon: LONGITUDE_GPS
gps_time: TIME_GPS
ctd_time: TIME
time: TIME
delta_time_s: DELTA_TIME_S
eng_pitchAng: PITCH
eng_rollAng: ROLL
eng_head: HEADING
ctd_depth: DEPTH
depth: DEPTH
pressure: PRES
ctd_pressure: PRES
conductivity: CNDC
trajectory: TRAJECTORY
aanderaa4330_dissolved_oxygen: DOXY
aanderaa4330_results_time: TIME_DOXY
sbe43_dissolved_oxygen: DOXY
sbe43_results_time: TIME_DOXY
dissolved_oxygen_sat: OXYSAT
oxygen_concentration: DOXY
chlorophyll: CHLA
sigma_theta: SIGTHETA
sigma_t: SIGMA_T
temperature: TEMP
temperature_raw: TEMP_RAW
salinity_raw: PSAL_RAW
conductivity_raw: CNDC_RAW
salinity: PSAL
absolute_salinity: SA
conservative_temperature: CT
ctd_density: DENSITY
density_insitu: DENSITY
profile_index: PROFILE_NUMBER
divenum: DIVE_NUMBER
platform: PLATFORM_MODEL
source: PLATFORM_SERIAL_NUMBER
vert_speed: GLIDER_VERT_VELO_MODEL
horz_speed: GLIDER_HORZ_VELO_MODEL
speed: GLIDE_SPEED
glide_angle: GLIDE_ANGLE
depth_avg_curr_east: DAVG_CURR_EAST
depth_avg_curr_north: DAVG_CURR_NORTH
depth_avg_curr_qc: DAVG_CURR_EAST_QC
adcp_Pressure: PRES_ADCP
eng_wlbb2f_blueRef: BBP470_REF
eng_wlbb2f_blueCount: BBP470
eng_wlbb2f_redCount: BBP700
eng_wlbb2f_redRef: BBP700_REF
eng_wlbb2f_VFtemp: BBP_VFTEMP ### What is the correct variable name for this?
eng_tempFreq: TEMP_FREQ ### What is the correct variable name for this?
eng_sbe43_O2Freq: O2_FREQ ### What is the correct variable name for this?
eng_condFreq: COND_FREQ ### What is the correct variable name for this?
particulate_backscatter: BBP700
backscatter_scaled: BBP700
backscatter_raw: RBBP700
potential_temperature: THETA
codaTODO_O2_saturation: OXYSAT
theta: THETA
down_irradiance_380: ED380
down_irradiance_490: ED490
downwelling_PAR: DPAR
temperature_oxygen: TEMP_OXYGEN
potential_density: POTDENS0
gsw_sigma0: POTDENS0
chlorophyll_raw: FLUOCHLA
eng_wlbb2f_fluorCount: FLUOCHLA
ad2cp_pitch: AD2CP_PITCH
ad2cp_roll: AD2CP_ROLL
ad2cp_heading: AD2CP_HEADING
ad2cp_time: AD2CP_TIME
ad2cp_pressure: AD2CP_PRES
turbidity: TURB
cdom: CDOM
cdom_raw: FLUOCDOM
phycoerythrin: PHYC
phycoerythrin_raw: FLUOPHYC
tke_dissipation_shear_1: EPSIFY01
tke_dissipation_shear_2: EPSIFY02
east_displacement: EAST_DISPLACEMENT
north_displacement: NORTH_DISPLACEMENT
eng_pitchCtl: PITCH_CTL
eng_rollCtl: ROLL_CTL
eng_vbdCC: VBD_CC
buoyancy: BUOYANCY
sound_velocity: SOUND_VELOCITY

#### SENSOR IDENTIFICATION ####
# Maps sensor keys found in dataset global attributes to full model names.
# These names act as keys to retrieve technical specs from OG1_sensor_attrs.yaml
sbe41: SeaBird SBE 41 CTD # Instrument information in OG1_sensor_attrs.yaml
wlbb2f: Wetlabs BB2FL-VMT # Instrument information in OG1_sensor_attrs.yaml
wlbbfl2: Wetlabs BB2FL-VMT # There are so many. Don't know if the correct one
wlbb2fl: Wetlabs BB2FL-VMT # There are so many. Don't know if the correct one
sbe43: Seabird SBE43F # Instrument information in OG1_sensor_attrs.yaml
legato: RBR legato CTD # Instrument information in OG1_sensor_attrs.yaml
codaTODO: RBR coda TODO # Instrument information in OG1_sensor_attrs.yaml
tridentebb700chla470fdom365: RBR tridente # Instrument information in OG1_sensor_attrs.yaml
aa4330: Aanderaa 4330 # Instrument information in OG1_sensor_attrs.yaml
aa4831: Aanderaa 4831 # Instrument information in OG1_sensor_attrs.yaml
qsp2150: Biospherical QSP 2150 # Instrument information in OG1_sensor_attrs.yaml
